import { firebaseConfig } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';

const app=initializeApp(firebaseConfig), auth=getAuth(app), db=getFirestore(app), provider=new GoogleAuthProvider();
const els=Object.fromEntries(['loginScreen','pendingScreen','appScreen','signInBtn','signOutBtn','pendingSignOutBtn','pendingEmail','registrationForm','registrationName','registrationPhone','registrationStatus','userAvatar','userName','courseList','lessonPane','learningPane','formatTabs','tagFilters','searchInput','authError','configWarning','welcomeMessage','languageBtn','modeTabs','resourceTools','topicsBtn','coursesPanel','academyBoard'].map(id=>[id,document.getElementById(id)]));
// Shared navigation tools belong below the page description in both Academy views.
els.modeTabs.before(els.resourceTools);
els.welcomeMessage.parentElement.insertAdjacentHTML('beforeend','<p class="page-description">Explore the Main Course and practical trading resources in one focused learning space.</p>');
const copy={
  en:{back:'Back to Meatika Trading',signout:'Sign out',start:'Start learning today',loginCopy:'Sign in to enter the Meatika Academy board, open every learning resource, and save your course progress.',signin:'Sign in with Google',firebase:'Firebase setup is still needed before Google sign-in can work. Add your Firebase project values in academy/firebase-config.js.',pending:'Access pending',pendingCopy:'Complete your registration below. An administrator will approve your Academy access.',fullName:'Full name',phone:'Phone number',submitRequest:'Submit registration',search:'Search learning content',courses:'Your courses',hello:'Hello',learner:'Learner',student:'Student',allLearning:'All learning',allTopics:'All topics',explore:'Explore Learning Center',viewAll:'View all',recommended:'Recommended for you',clear:'Clear search',noMatch:'Nothing matched your search or topic yet.',open:'Open this learning resource in Meatika Academy.',backBoard:'← Back to learning board',resource:'Learning Center resource',lessons:'lessons',lesson:'Lesson'},
  km:{back:'ត្រឡប់ទៅ Meatika Trading',signout:'ចាកចេញ',start:'ចាប់ផ្តើមរៀនថ្ងៃនេះ',loginCopy:'ចូលគណនីដើម្បីចូលទៅកាន់ផ្ទាំង Meatika Academy បើកមើលមាតិកាសិក្សាទាំងអស់ និងរក្សាទុកវឌ្ឍនភាពវគ្គសិក្សារបស់អ្នក។',signin:'ចូលដោយ Google',firebase:'ត្រូវរៀបចំ Firebase ជាមុនសិន ដើម្បីប្រើការចូលដោយ Google។ សូមបញ្ចូលតម្លៃគម្រោងរបស់អ្នកក្នុង academy/firebase-config.js។',pending:'កំពុងរង់ចាំការអនុម័ត',pendingCopy:'សូមបំពេញការចុះឈ្មោះខាងក្រោម។ អ្នកគ្រប់គ្រងនឹងអនុម័តការចូល Academy របស់អ្នក។',fullName:'ឈ្មោះពេញ',phone:'លេខទូរស័ព្ទ',submitRequest:'ដាក់ស្នើការចុះឈ្មោះ',search:'ស្វែងរកមាតិកាសិក្សា',courses:'វគ្គសិក្សារបស់អ្នក',hello:'សួស្តី',learner:'អ្នកសិក្សា',student:'សិស្ស',allLearning:'មាតិកាទាំងអស់',allTopics:'ប្រធានបទទាំងអស់',explore:'ស្វែងរកមជ្ឈមណ្ឌលសិក្សា',viewAll:'មើលទាំងអស់',recommended:'ណែនាំសម្រាប់អ្នក',clear:'លុបការស្វែងរក',noMatch:'មិនមានមាតិកាត្រូវនឹងការស្វែងរក ឬប្រធានបទនេះទេ។',open:'បើកមើលមាតិកាសិក្សានេះក្នុង Meatika Academy.',backBoard:'← ត្រឡប់ទៅផ្ទាំងសិក្សា',resource:'មាតិកាពីមជ្ឈមណ្ឌលសិក្សា',lessons:'មេរៀន',lesson:'មេរៀន'}
};
copy.en.pending='Registration pending approval';copy.en.pendingCopy='Your name and phone number are required. An administrator must approve your Academy access.';copy.en.submitRequest='Submit registration';copy.en.search='Search Main Course and Resources';
let lang='en';try{lang=localStorage.getItem('academy-lang')==='km'?'km':'en'}catch(e){}
let academyData,siteData,currentUser,userProgress={},activeCourseId,activeLessonId,activeFormat='all',activeTag='all',activeContentId=null,activeArea='resources';
const t=k=>copy[lang][k]||copy.en[k]||k, pick=o=>typeof o==='string'?o:(o?.[lang]||o?.en||''), esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titleOf=x=>pick(x?.title)||'Untitled';
function applyLocale(){document.documentElement.lang=lang==='km'?'km':'en';document.body.classList.toggle('km',lang==='km');document.querySelectorAll('[data-i18n]').forEach(x=>x.textContent=t(x.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(x=>x.placeholder=t(x.dataset.i18nPlaceholder));els.languageBtn.textContent=lang==='en'?'ខ្មែរ':'EN';if(currentUser)els.welcomeMessage.textContent=`${t('hello')}, ${(currentUser.displayName||t('learner')).split(' ')[0]}`;if(siteData)render()}
els.languageBtn.onclick=()=>{lang=lang==='en'?'km':'en';try{localStorage.setItem('academy-lang',lang)}catch(e){}applyLocale()};applyLocale();
if(firebaseConfig.apiKey.startsWith('PASTE_'))els.configWarning.style.display='block';
els.signInBtn.onclick=async()=>{els.authError.textContent='';try{await signInWithPopup(auth,provider)}catch(e){console.error(e);els.authError.textContent=lang==='km'?'ការចូលគណនីបរាជ័យ។ សូមព្យាយាមម្ដងទៀត។':'Sign-in failed. Please try again.'}};els.signOutBtn.onclick=()=>signOut(auth);els.pendingSignOutBtn.onclick=()=>signOut(auth);
els.registrationForm.onsubmit=async e=>{e.preventDefault();if(!currentUser?.email)return;const displayName=els.registrationName.value.trim(),phone=els.registrationPhone.value.trim();if(!displayName||!phone)return;els.registrationStatus.textContent='';try{await setDoc(doc(db,'accessRequests',currentUser.email.toLowerCase()),{email:currentUser.email.toLowerCase(),displayName,phone,photoURL:currentUser.photoURL||'',requestedAt:new Date().toISOString()},{merge:true});els.registrationStatus.style.color='#37a56d';els.registrationStatus.textContent='Registration submitted. Please wait for administrator approval.'}catch(err){els.registrationStatus.textContent=err.message||'Could not submit registration.'}};
function showScreen(name){els.loginScreen.style.display=name==='login'?'flex':'none';els.pendingScreen.style.display=name==='pending'?'flex':'none';els.appScreen.style.display=name==='app'?'block':'none';window.dispatchEvent(new CustomEvent('academy-auth',{detail:{signedIn:name!=='login'}}));}
async function approved(user){return !!user.email&&(await getDoc(doc(db,'approvedStudents',user.email.toLowerCase()))).exists()}
async function openAcademy(){els.userName.textContent=currentUser.displayName||currentUser.email||t('student');if(currentUser.photoURL)els.userAvatar.src=currentUser.photoURL;await Promise.all([loadProgress(),loadData()]);showScreen('app');openFromHash();applyLocale();}
onAuthStateChanged(auth,async user=>{currentUser=user;if(!user)return showScreen('login');let ok=false;try{ok=await approved(user)}catch(e){console.error(e)}if(!ok){els.registrationName.value=user.displayName||'';els.pendingEmail.textContent=user.email||'';return showScreen('pending')}await openAcademy();});
async function loadProgress(){const s=await getDoc(doc(db,'users',currentUser.uid));userProgress=(s.exists()&&s.data().completedLessons)||{}}
async function saveProgress(){await setDoc(doc(db,'users',currentUser.uid),{completedLessons:userProgress,displayName:currentUser.displayName||null,email:currentUser.email||null,updatedAt:new Date().toISOString()},{merge:true})}
async function loadData(){const [a,s]=await Promise.all([fetch('academy-data.json',{cache:'no-store'}).then(r=>r.json()),fetch('../data.json',{cache:'no-store'}).then(r=>r.json())]);academyData=a;siteData=s}
function setHash(v){history.pushState(null,'',v?`#${v}`:location.pathname)}function openFromHash(){const h=decodeURIComponent(location.hash.slice(1));if(h.startsWith('content=')){activeContentId=h.slice(8);activeCourseId=null;activeArea='resources'}else if(h.startsWith('course=')){activeCourseId=h.slice(7);activeContentId=null;activeArea='course'}}window.addEventListener('popstate',()=>{openFromHash();render()});
const allContent=()=>window.MTHNews?MTHNews.publishedNews(siteData):(siteData.news||[]).filter(x=>x.published!==false);const formatOf=x=>window.MTHNews?MTHNews.formatInfo(x).label.toLowerCase():(x.format||'article');const thumb=x=>x.cover||(x.video?.type==='file'&&window.MTHSite?.cloudinaryVideoPosterUrl(x.video.file))||'';
function renderModes(){els.modeTabs.innerHTML=`<button class="mode-tab ${activeArea==='course'?'active':''}" data-mode="course">${lang==='km'?'វគ្គសិក្សាសំខាន់':'Main Course'}</button><button class="mode-tab ${activeArea==='resources'?'active':''}" data-mode="resources">${lang==='km'?'ធនធាន':'Resources'}</button>`;els.modeTabs.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{activeArea=b.dataset.mode;activeContentId=null;if(activeArea==='course')activeCourseId=activeCourseId||academyData.courses[0]?.id;else activeCourseId=null;setHash(activeCourseId?`course=${encodeURIComponent(activeCourseId)}`:'');render()})}
function renderTabs(){const fs=[{id:'all',label:t('allLearning')},...(siteData.learningFormats||[]).map(x=>({id:x.id,label:pick(x.title)||x.id}))];els.formatTabs.innerHTML=fs.map(x=>`<button class="tab ${activeFormat===x.id?'active':''}" data-format="${esc(x.id)}">${esc(x.label)}</button>`).join('');els.formatTabs.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>{activeFormat=b.dataset.format;activeContentId=activeCourseId=null;activeArea='resources';setHash('');render()})}
function renderTags(){const tags=[{id:'all',en:t('allTopics')},...(siteData.newsTags||[])];els.tagFilters.innerHTML=tags.map(x=>`<button class="topic-option ${activeTag===x.id?'active':''}" data-tag="${esc(x.id)}">${esc(pick(x))}</button>`).join('');els.tagFilters.querySelectorAll('[data-tag]').forEach(b=>b.onclick=()=>{activeTag=b.dataset.tag;activeContentId=null;if(activeArea==='resources')activeCourseId=null;els.tagFilters.classList.remove('open');setHash(activeArea==='course'&&activeCourseId?`course=${encodeURIComponent(activeCourseId)}`:'');render()});els.topicsBtn.onclick=()=>els.tagFilters.classList.toggle('open')}
function renderBoard(){const q=(els.searchInput.value||'').trim().toLowerCase();let list=allContent().filter(x=>(activeFormat==='all'||formatOf(x)===activeFormat)&&(activeTag==='all'||x.category===activeTag));if(q)list=list.filter(x=>`${pick(x.title)} ${pick(x.excerpt)} ${(x.title?.en||'')} ${(x.title?.km||'')}`.toLowerCase().includes(q));const fs=siteData.learningFormats||[];const formats=activeFormat==='all'?`<div class="section-head"><h2>${t('explore')}</h2><button id="viewAll">${t('viewAll')}</button></div><div class="format-row">${fs.map((x,i)=>`<button class="format-card" data-format="${esc(x.id)}"><span class="format-icon">${['▤','▶','♫','▣'][i]||'✦'}</span><strong>${esc(pick(x.title)||x.id)}</strong><span>${esc(pick(x.desc)||'')}</span></button>`).join('')}</div>`:'';els.learningPane.innerHTML=`${formats}<div class="section-head"><h2>${activeFormat==='all'?t('recommended'):esc(pick(fs.find(x=>x.id===activeFormat)?.title)||activeFormat)}</h2><button id="clearSearch" ${q?'':'style="display:none"'}>${t('clear')}</button></div>${list.length?`<div class="content-grid">${list.map(card).join('')}</div>`:`<p class="empty-message">${t('noMatch')}</p>`}`;els.learningPane.querySelectorAll('.format-card').forEach(b=>b.onclick=()=>{activeFormat=b.dataset.format;render()});const v=els.learningPane.querySelector('#viewAll');if(v)v.onclick=()=>{activeFormat='all';render()};const c=els.learningPane.querySelector('#clearSearch');if(c)c.onclick=()=>{els.searchInput.value='';render()};els.learningPane.querySelectorAll('.content-card').forEach(b=>b.onclick=()=>{activeContentId=b.dataset.id;activeCourseId=null;setHash(`content=${encodeURIComponent(activeContentId)}`);render()})}
function card(x){const type=formatOf(x),im=thumb(x);return `<button class="content-card" data-id="${esc(x.id)}"><div class="content-thumb ${im?'':'empty'}" ${im?`style="background-image:url('${esc(im)}')"`:''}><span class="type-pill">${esc(type)}</span><span class="play-dot">${type==='audio'?'♫':type==='book'?'↗':'▶'}</span></div><h3>${esc(titleOf(x))}</h3><p>${esc(pick(x.excerpt)||t('open'))}</p></button>`}
function renderContentDetail(){const x=allContent().find(x=>x.id===activeContentId);if(!x){activeContentId=null;return renderBoard()}const im=thumb(x),type=formatOf(x);let media='',tracks=[];if(type==='video')media=window.MTHNews?.videoEmbedHtml(x.video)||'';else if(type==='audio'){tracks=x.audioTracks?.length?x.audioTracks:(x.audioUrl?[{title:titleOf(x),url:x.audioUrl}]:[]);media=tracks.length?`<div class="mp3-player"><div class="mp3-label">MP3 Player</div><div class="mp3-title" id="mp3Title"></div><audio id="mp3Audio" preload="metadata"></audio><input class="mp3-progress" id="mp3Progress" type="range" min="0" max="100" value="0"><div class="mp3-time"><span id="mp3Current">0:00</span><span id="mp3Duration">0:00</span></div><div class="mp3-controls"><button id="mp3Shuffle" title="Shuffle">⇄</button><button id="mp3Prev" title="Previous">⏮</button><button class="mp3-play" id="mp3Play">▶</button><button id="mp3Next" title="Next">⏭</button></div><div class="mp3-tracklist">${tracks.map((a,i)=>`<button class="mp3-track" data-track="${i}">${i+1}. ${esc(a.title||titleOf(x))}</button>`).join('')}</div></div>`:''}else if(type==='book'&&x.bookUrl){const previewUrl=window.MTHNews?.pdfPreviewUrl?window.MTHNews.pdfPreviewUrl(x.bookUrl):x.bookUrl;media=`<div class="media"><iframe class="book-frame" src="${esc(previewUrl)}#view=FitH" title="${esc(titleOf(x))}" loading="lazy"></iframe></div><p class="book-actions"><a href="${esc(previewUrl)}" target="_blank" rel="noopener">${lang==='km'?'អានពេញអេក្រង់':'Read full screen'}</a></p>`}els.learningPane.innerHTML=`<article class="detail"><button class="detail-back" id="backToBoard">${t('backBoard')}</button><div class="detail-hero ${im?'':'empty'}" ${im?`style="background-image:url('${esc(im)}')"`:''}></div><h2>${esc(titleOf(x))}</h2><p class="lead">${esc(pick(x.excerpt)||t('resource'))}</p>${media}<div class="detail-body">${window.MTHNews?.bodyHtml(pick(x.body)||'')||''}</div></article>`;els.learningPane.querySelector('#backToBoard').onclick=()=>{activeContentId=null;setHash('');render()};if(type==='audio'&&tracks.length)wireMp3(tracks)}
function wireMp3(tracks){const a=document.getElementById('mp3Audio'),title=document.getElementById('mp3Title'),play=document.getElementById('mp3Play'),progress=document.getElementById('mp3Progress'),cur=document.getElementById('mp3Current'),dur=document.getElementById('mp3Duration'),fmt=s=>`${Math.floor(s/60)||0}:${String(Math.floor(s%60)||0).padStart(2,'0')}`;let i=0,shuffle=false;const load=(n,auto=true)=>{i=(n+tracks.length)%tracks.length;a.src=tracks[i].url;title.textContent=tracks[i].title||`Track ${i+1}`;document.querySelectorAll('.mp3-track').forEach(x=>x.classList.toggle('active',+x.dataset.track===i));if(auto)a.play().catch(()=>{})};play.onclick=()=>a.paused?a.play():a.pause();a.onplay=()=>play.textContent='❚❚';a.onpause=()=>play.textContent='▶';a.ontimeupdate=()=>{progress.value=a.duration?a.currentTime/a.duration*100:0;cur.textContent=fmt(a.currentTime)};a.onloadedmetadata=()=>dur.textContent=fmt(a.duration);progress.oninput=()=>{if(a.duration)a.currentTime=a.duration*progress.value/100};document.getElementById('mp3Prev').onclick=()=>load(i-1);document.getElementById('mp3Next').onclick=()=>load(shuffle?Math.floor(Math.random()*tracks.length):i+1);document.getElementById('mp3Shuffle').onclick=e=>{shuffle=!shuffle;e.currentTarget.classList.toggle('is-on',shuffle)};a.onended=()=>document.getElementById('mp3Next').click();document.querySelectorAll('.mp3-track').forEach(x=>x.onclick=()=>load(+x.dataset.track));load(0,false)}
const findCourse=id=>academyData.courses.find(x=>x.id===id);const progress=c=>{const total=c.lessons.length,done=c.lessons.filter(x=>userProgress[x.id]).length;return{total,done,pct:total?Math.round(done/total*100):0}};
// Editors can paste normal share/watch URLs. Only known player hosts become iframes.
const embedUrl=url=>{const v=String(url||'').trim();let m=v.match(/(?:youtu\.be\/|(?:www\.)?(?:youtube\.com|music\.youtube\.com)\/(?:watch\?(?:.*&)?v=|embed\/|shorts\/))([\w-]{6,})/i);if(m)return `https://www.youtube-nocookie.com/embed/${m[1]}?rel=0&modestbranding=1&iv_load_policy=3`;m=v.match(/vimeo\.com\/(?:video\/)?(\d+)/i);if(m)return `https://player.vimeo.com/video/${m[1]}`;const vevo=v.match(/(?:vevo\.com\/(?:watch\/)?[^/?#]+\/[^/?#]+\/|embed\.vevo\.com\/?\?isrc=)([A-Z]{2}[A-Z0-9]{10})/i);return vevo?`https://embed.vevo.com/?isrc=${vevo[1]}`:v};
const courseMatches=(c,q)=>!q||`${pick(c.title)} ${pick(c.description)} ${c.lessons.map(l=>`${pick(l.title)} ${pick(l.description)}`).join(' ')}`.toLowerCase().includes(q);
const filteredCourses=()=>{const q=(els.searchInput.value||'').trim().toLowerCase();return academyData.courses.filter(c=>(activeTag==='all'||c.tag===activeTag)&&courseMatches(c,q))};
function renderCourses(){const courses=filteredCourses();els.courseList.innerHTML=courses.map(c=>{const p=progress(c);return `<article class="course-card ${c.id===activeCourseId?'active':''}" data-course="${esc(c.id)}"><h3>${esc(pick(c.title))}</h3><p>${esc(pick(c.description))}</p><div class="course-progress"><span>${p.done}/${p.total} ${t('lessons')}</span><div class="track"><i style="width:${p.pct}%"></i></div><span>${p.pct}%</span></div></article>`}).join('')||'<p class="empty-message">No courses match this search or topic.</p>';els.courseList.querySelectorAll('[data-course]').forEach(x=>x.onclick=()=>{activeCourseId=x.dataset.course;activeLessonId=activeContentId=null;setHash(`course=${encodeURIComponent(activeCourseId)}`);render()})}
function renderCourse(){const c=findCourse(activeCourseId);if(!c)return renderBoard();const q=(els.searchInput.value||'').trim().toLowerCase(), matchingLessons=c.lessons.filter(x=>!q||`${pick(c.title)} ${pick(c.description)}`.toLowerCase().includes(q)||`${pick(x.title)} ${pick(x.description)}`.toLowerCase().includes(q));activeLessonId=matchingLessons.some(x=>x.id===activeLessonId)?activeLessonId:matchingLessons[0]?.id;const l=c.lessons.find(x=>x.id===activeLessonId);els.lessonPane.innerHTML=`<section class="course-view"><button class="detail-back" id="backToBoard">${t('backBoard')}</button><h2>${esc(pick(c.title))}</h2><p>${esc(pick(c.description))}</p><div class="lesson-list">${matchingLessons.map(x=>{const i=c.lessons.indexOf(x);return `<label class="lesson ${x.id===activeLessonId?'active':''}" data-lesson="${esc(x.id)}"><input class="lesson-check" type="checkbox" data-check="${esc(x.id)}" ${userProgress[x.id]?'checked':''}><span><strong class="lesson-title">${i+1}. ${esc(pick(x.title))}</strong><br><span class="lesson-time">${esc(x.duration||t('lesson'))}</span></span><span>›</span></label>`}).join('')}</div>${l?`<div class="lesson-stage">${l.videoUrl?`<div class="media" oncontextmenu="return false"><iframe src="${esc(embedUrl(l.videoUrl))}" title="${esc(pick(l.title))}" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture; fullscreen" allowfullscreen sandbox="allow-scripts allow-same-origin allow-presentation allow-popups allow-popups-to-escape-sandbox"></iframe></div>`:''}<h3>${esc(pick(l.title))}</h3><p>${esc(pick(l.description))}</p></div>`:''}</section>`;els.lessonPane.querySelector('#backToBoard').onclick=()=>{activeCourseId=activeLessonId=null;setHash('');render()};els.lessonPane.querySelectorAll('[data-lesson]').forEach(x=>x.onclick=e=>{if(e.target.matches('[data-check]'))return;activeLessonId=x.dataset.lesson;renderCourse()});els.lessonPane.querySelectorAll('[data-check]').forEach(x=>x.onchange=async()=>{userProgress[x.dataset.check]=x.checked;await saveProgress();render()})}
function resourceStripHtml(){const list=allContent().slice().sort((a,b)=>new Date(b.publishedAt||0)-new Date(a.publishedAt||0)).slice(0,4);if(!list.length)return '';return `<div class="resource-strip"><div class="section-head"><h2>${lang==='km'?'ធនធានថ្មីៗបំផុត':'Recently added resources'}</h2><button id="viewAllResources">${t('viewAll')}</button></div><div class="content-grid-4">${list.map(card).join('')}</div></div>`}
function wireResourceStrip(){const v=els.learningPane.querySelector('#viewAllResources');if(v)v.onclick=()=>{activeArea='resources';activeFormat='all';activeContentId=null;setHash('');render()};els.learningPane.querySelectorAll('.content-card').forEach(b=>b.onclick=()=>{activeArea='resources';activeContentId=b.dataset.id;activeCourseId=null;setHash(`content=${encodeURIComponent(activeContentId)}`);render()})}
function render(){renderModes();const resources=activeArea==='resources';els.formatTabs.style.display=resources?'flex':'none';els.resourceTools.style.display='flex';els.coursesPanel.style.display=resources?'none':'block';els.academyBoard.style.gridTemplateColumns=resources?'1fr':'1fr 310px';renderTabs();renderTags();els.lessonPane.innerHTML='';if(resources){els.learningPane.innerHTML='';if(activeContentId)renderContentDetail();else renderBoard()}else{els.learningPane.innerHTML=resourceStripHtml();wireResourceStrip();renderCourse()}renderCourses()}els.searchInput.addEventListener('input',()=>{if(activeArea==='resources'&&!activeContentId)renderBoard();else if(activeArea==='course'){const matches=filteredCourses();if(matches.length&&!matches.some(c=>c.id===activeCourseId)){activeCourseId=matches[0].id;activeLessonId=null}render()}});
