import { firebaseConfig } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';

const app = initializeApp(firebaseConfig), auth = getAuth(app), db = getFirestore(app), provider = new GoogleAuthProvider();
const els = Object.fromEntries(['loginScreen','pendingScreen','appScreen','signInBtn','signOutBtn','pendingSignOutBtn','pendingEmail','userAvatar','userName','courseList','lessonPane','learningPane','formatTabs','searchInput','authError','configWarning','welcomeMessage'].map(id=>[id,document.getElementById(id)]));
let academyData, siteData, currentUser, userProgress = {}, activeCourseId, activeLessonId, activeFormat = 'all', activeContentId = null;
const esc = v => String(v || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titleOf = x => (x && x.title && x.title.en) || 'Untitled';

if (firebaseConfig.apiKey.startsWith('PASTE_')) els.configWarning.style.display = 'block';
els.signInBtn.addEventListener('click', async()=>{els.authError.textContent='';try{await signInWithPopup(auth,provider)}catch(e){console.error(e);els.authError.textContent='Sign-in failed. Please try again.'}});
els.signOutBtn.addEventListener('click',()=>signOut(auth)); els.pendingSignOutBtn.addEventListener('click',()=>signOut(auth));
function showScreen(name){els.loginScreen.style.display=name==='login'?'flex':'none';els.pendingScreen.style.display=name==='pending'?'flex':'none';els.appScreen.style.display=name==='app'?'block':'none';window.dispatchEvent(new CustomEvent('academy-auth',{detail:{signedIn:name!=='login'}}));}
async function approved(user){return !!user.email && (await getDoc(doc(db,'approvedStudents',user.email.toLowerCase()))).exists()}
onAuthStateChanged(auth,async user=>{currentUser=user;if(!user)return showScreen('login');let ok=false;try{ok=await approved(user)}catch(e){console.error('Approval check failed',e)}if(!ok){els.pendingEmail.textContent=user.email||'';return showScreen('pending')}els.userName.textContent=user.displayName||user.email||'Student';els.welcomeMessage.textContent=`Hello, ${(user.displayName||'Learner').split(' ')[0]}`;if(user.photoURL)els.userAvatar.src=user.photoURL;await Promise.all([loadProgress(),loadData()]);showScreen('app');openFromHash();render();});
async function loadProgress(){const snap=await getDoc(doc(db,'users',currentUser.uid));userProgress=(snap.exists()&&snap.data().completedLessons)||{}}
async function saveProgress(){await setDoc(doc(db,'users',currentUser.uid),{completedLessons:userProgress,displayName:currentUser.displayName||null,email:currentUser.email||null,updatedAt:new Date().toISOString()},{merge:true})}
async function loadData(){const [courses,site]=await Promise.all([fetch('academy-data.json',{cache:'no-store'}).then(r=>r.json()),fetch('../data.json',{cache:'no-store'}).then(r=>r.json())]);academyData=courses;siteData=site}
function setHash(value){history.pushState(null,'',value?`#${value}`:location.pathname)}
function openFromHash(){const h=decodeURIComponent(location.hash.slice(1));if(h.startsWith('content=')){activeContentId=h.slice(8);activeCourseId=null}else if(h.startsWith('course=')){activeCourseId=h.slice(7);activeContentId=null}}
window.addEventListener('popstate',()=>{openFromHash();render()});
function allContent(){return window.MTHNews?MTHNews.publishedNews(siteData):(siteData.news||[]).filter(x=>x.published!==false)}
function formatOf(item){return window.MTHNews?MTHNews.formatInfo(item).label.toLowerCase():(item.format||'article')}
function thumb(item){const poster=item.video&&item.video.type==='file'&&window.MTHSite?.cloudinaryVideoPosterUrl(item.video.file);return item.cover||poster||''}
function renderTabs(){const formats=[{id:'all',label:'All learning' },...(siteData.learningFormats||[]).map(x=>({id:x.id,label:(x.title&&x.title.en)||x.id}))];els.formatTabs.innerHTML=formats.map(x=>`<button class="tab ${activeFormat===x.id?'active':''}" data-format="${esc(x.id)}">${esc(x.label)}</button>`).join('');els.formatTabs.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>{activeFormat=b.dataset.format;activeContentId=null;activeCourseId=null;setHash('');render()})}
function renderBoard(){const query=(els.searchInput.value||'').trim().toLowerCase();let list=allContent().filter(x=>activeFormat==='all'||formatOf(x)===activeFormat);if(query)list=list.filter(x=>`${titleOf(x)} ${(x.excerpt&&x.excerpt.en)||''}`.toLowerCase().includes(query));const formats=(siteData.learningFormats||[]);const formatCards=activeFormat==='all'?`<div class="section-head"><h2>Explore Learning Center</h2><button id="viewAll">View all</button></div><div class="format-row">${formats.map((x,i)=>`<button class="format-card" data-format="${esc(x.id)}"><span class="format-icon">${['▤','▶','♫','▣'][i]||'✦'}</span><strong>${esc((x.title&&x.title.en)||x.id)}</strong><span>${esc((x.desc&&x.desc.en)||'Explore content')}</span></button>`).join('')}</div>`:'';els.learningPane.innerHTML=`${formatCards}<div class="section-head"><h2>${activeFormat==='all'?'Recommended for you':esc((formats.find(x=>x.id===activeFormat)?.title||{}).en||activeFormat)}</h2><button id="clearSearch" ${query?'':'style="display:none"'}>Clear search</button></div>${list.length?`<div class="content-grid">${list.map(card).join('')}</div>`:'<p class="empty-message">Nothing matched your search yet.</p>'}`;els.learningPane.querySelectorAll('.format-card').forEach(b=>b.onclick=()=>{activeFormat=b.dataset.format;render()});const view=els.learningPane.querySelector('#viewAll');if(view)view.onclick=()=>{activeFormat='all';render()};const clear=els.learningPane.querySelector('#clearSearch');if(clear)clear.onclick=()=>{els.searchInput.value='';render()};els.learningPane.querySelectorAll('.content-card').forEach(b=>b.onclick=()=>{activeContentId=b.dataset.id;activeCourseId=null;setHash(`content=${encodeURIComponent(activeContentId)}`);render()})}
function card(item){const type=formatOf(item), image=thumb(item);return `<button class="content-card" data-id="${esc(item.id)}"><div class="content-thumb ${image?'':'empty'}" ${image?`style="background-image:url('${esc(image)}')"`:''}><span class="type-pill">${esc(type)}</span><span class="play-dot">${type==='audio'?'♫':type==='book'?'↗':'▶'}</span></div><h3>${esc(titleOf(item))}</h3><p>${esc((item.excerpt&&item.excerpt.en)||'Open this learning resource in Meatika Academy.')}</p></button>`}
function renderContentDetail(){const item=allContent().find(x=>x.id===activeContentId);if(!item){activeContentId=null;return renderBoard()}const image=thumb(item),type=formatOf(item);let media='';if(type==='video')media=window.MTHNews?.videoEmbedHtml(item.video)||'';else if(type==='audio'){const tracks=(item.audioTracks?.length?item.audioTracks:(item.audioUrl?[{title:titleOf(item),url:item.audioUrl}]:[]));media=tracks.length?`<div class="media">${tracks.map(t=>`<p><strong>${esc(t.title||titleOf(item))}</strong><audio controls src="${esc(t.url)}"></audio></p>`).join('')}</div>`:''}else if(type==='book'&&item.bookUrl)media=`<div class="media"><iframe class="book-frame" src="${esc(item.bookUrl)}#view=FitH" title="${esc(titleOf(item))}"></iframe></div>`;els.learningPane.innerHTML=`<article class="detail"><button class="detail-back" id="backToBoard">← Back to learning board</button><div class="detail-hero ${image?'':'empty'}" ${image?`style="background-image:url('${esc(image)}')"`:''}></div><h2>${esc(titleOf(item))}</h2><p class="lead">${esc((item.excerpt&&item.excerpt.en)||'Learning Center resource')}</p>${media}<div class="detail-body">${window.MTHNews?.bodyHtml((item.body&&item.body.en)||'')||''}</div></article>`;els.learningPane.querySelector('#backToBoard').onclick=()=>{activeContentId=null;setHash('');render()}}
function findCourse(id){return academyData.courses.find(x=>x.id===id)}
function progress(course){const total=course.lessons.length,done=course.lessons.filter(x=>userProgress[x.id]).length;return{total,done,pct:total?Math.round(done/total*100):0}}
function renderCourses(){els.courseList.innerHTML=academyData.courses.map(c=>{const p=progress(c);return `<article class="course-card ${c.id===activeCourseId?'active':''}" data-course="${esc(c.id)}"><h3>${esc(c.title.en)}</h3><p>${esc(c.description.en)}</p><div class="course-progress"><span>${p.done}/${p.total} lessons</span><div class="track"><i style="width:${p.pct}%"></i></div><span>${p.pct}%</span></div></article>`}).join('');els.courseList.querySelectorAll('[data-course]').forEach(x=>x.onclick=()=>{activeCourseId=x.dataset.course;activeLessonId=null;activeContentId=null;setHash(`course=${encodeURIComponent(activeCourseId)}`);render()})}
function renderCourse(){const c=findCourse(activeCourseId);if(!c)return renderBoard();activeLessonId=activeLessonId||c.lessons[0]?.id;const lesson=c.lessons.find(x=>x.id===activeLessonId);els.lessonPane.innerHTML=`<section class="course-view"><button class="detail-back" id="backToBoard">← Learning board</button><h2>${esc(c.title.en)}</h2><p>${esc(c.description.en)}</p><div class="lesson-list">${c.lessons.map((x,i)=>`<label class="lesson ${x.id===activeLessonId?'active':''}" data-lesson="${esc(x.id)}"><input class="lesson-check" type="checkbox" data-check="${esc(x.id)}" ${userProgress[x.id]?'checked':''}><span><strong class="lesson-title">${i+1}. ${esc(x.title.en)}</strong><br><span class="lesson-time">${esc(x.duration||'Lesson')}</span></span><span>›</span></label>`).join('')}</div>${lesson?`<div class="lesson-stage">${lesson.videoUrl?`<div class="media"><iframe src="${esc(lesson.videoUrl)}" allow="autoplay;encrypted-media;picture-in-picture" allowfullscreen></iframe></div>`:''}<h3>${esc(lesson.title.en)}</h3><p>${esc(lesson.description.en)}</p></div>`:''}</section>`;els.lessonPane.querySelector('#backToBoard').onclick=()=>{activeCourseId=null;activeLessonId=null;setHash('');render()};els.lessonPane.querySelectorAll('[data-lesson]').forEach(x=>x.onclick=e=>{if(e.target.matches('[data-check]'))return;activeLessonId=x.dataset.lesson;renderCourse()});els.lessonPane.querySelectorAll('[data-check]').forEach(x=>x.onchange=async()=>{userProgress[x.dataset.check]=x.checked;await saveProgress();render()})}
function render(){renderTabs();els.lessonPane.innerHTML='';if(activeContentId)renderContentDetail();else if(activeCourseId)renderCourse();else renderBoard();renderCourses()}
els.searchInput.addEventListener('input',()=>{if(!activeContentId&&!activeCourseId)renderBoard()});
